version: "3.9"

services:
  recipe-app-api:
    build: .
    
    ports:
      - 8000:8000
    
    volumes:
      - .:/recipe-app-api
    
    command: > # > symbol enables multiline commands
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"    

    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=unodostres

    depends_on:
      - db

    container_name: "recipe-app-api-ctr"

  db:
    image: postgres:13-alpine
    
    volumes:
      - recipe-app-dev-db:/var/lib/postgresql/data
    
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=unodostres

    container_name: "recipe-app-dev-db-ctr"

volumes:
  recipe-app-dev-db:
  