# Generated by Django 4.2 on 2024-12-17 01:33

import core_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_ingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=core_app.models.recipe_image_file_path),
        ),
    ]
