---
name: Checks # name of the action

on: [push] # trigger of the action

jobs: 
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
        # 1. login to docker hub
      - name: Login to Docker Hub 
        uses: docker/login-action@v3
        with:
          # use secrets stored in github
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

        # 2. pull source code
      - name: Checkout 
        uses: actions/checkout@v2

        # 3. run unit tests
      - name: Run unit tests 
        run: docker compose run --rm recipe-app-api sh -c "python manage.py test"
